// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDklo95QYbj4PGZeKAqRBBzCfFKc9CFoXs',
    appId: '1:672243562252:web:fa94020bf1184b4d817b29',
    messagingSenderId: '672243562252',
    projectId: 'mp-lpo-connect',
    authDomain: 'mp-lpo-connect.firebaseapp.com',
    storageBucket: 'mp-lpo-connect.firebasestorage.app',
    measurementId: 'G-EBKDN66SWJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1lEwa0LwBhvn2mUo9egkoFMcmxjTjmyo',
    appId: '1:672243562252:android:8e902e1f38e7b0c9817b29',
    messagingSenderId: '672243562252',
    projectId: 'mp-lpo-connect',
    storageBucket: 'mp-lpo-connect.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx6zwPyeAORLOBnPQ00eSQUQMJq4Q1z94',
    appId: '1:672243562252:ios:79270ff3db523a0b817b29',
    messagingSenderId: '672243562252',
    projectId: 'mp-lpo-connect',
    storageBucket: 'mp-lpo-connect.firebasestorage.app',
    iosBundleId: 'com.lpoconnect.lpoConnectApp',
  );
}
